.gitignore

So I don't accidentally commit `.idea`

Initial gitignore

---

.buildkite/pipeline.yml
aggregator/Dockerfile
aggregator/src/main/resources/application.conf
aggregator/src/main/resources/logback.xml
aggregator/src/main/scala/weco/concepts/aggregator/Main.scala
aggregator/src/test/scala/weco/concepts/aggregator/AggregatorTest.scala
build.sbt
docker-compose.test.yml
docker-compose.yml
infrastructure/ecr.tf
project/Dependencies.scala

https://github.com/wellcomecollection/concepts-pipeline/issues/5

skeleton app for the aggregator

---

ingestor/src/main/scala/weco/concepts/ingestor/IngestStream.scala
ingestor/src/main/scala/weco/concepts/ingestor/Main.scala
ingestor/src/main/scala/weco/concepts/ingestor/stages/Fetcher.scala
ingestor/src/test/scala/weco/concepts/ingestor/stages/FetcherTest.scala
project/Dependencies.scala

This adds the first stage of the design in https://github.com/wellcomecollection/docs/tree/main/rfcs/051-concepts-adapters: it fetches the gzipped bulk export of concepts from the library of congress.
Closes https://github.com/wellcomecollection/concepts-pipeline/issues/6

Stream the LCSH export

---

ingestor/src/main/scala/weco/concepts/ingestor/IngestStream.scala
ingestor/src/main/scala/weco/concepts/ingestor/stages/Scroll.scala
ingestor/src/test/scala/weco/concepts/ingestor/stages/ScrollTest.scala

Does what it says, not much to it
Closes https://github.com/wellcomecollection/concepts-pipeline/issues/34

Decompress and split into lines the downloaded file

---

ingestor/src/main/scala/weco/concepts/ingestor/IngestStream.scala
ingestor/src/main/scala/weco/concepts/ingestor/json/JsonOps.scala
ingestor/src/main/scala/weco/concepts/ingestor/model/Concept.scala
ingestor/src/main/scala/weco/concepts/ingestor/model/Identifier.scala
ingestor/src/main/scala/weco/concepts/ingestor/stages/Transformer.scala
ingestor/src/test/scala/weco/concepts/ingestor/stages/TransformerTest.scala
project/Dependencies.scala

Does what it says - will add some comments about my rationale to the PR!
Closes https://github.com/wellcomecollection/concepts-pipeline/issues/7

Transform LCSH concepts to our internal model

---

ingestor/src/main/resources/application.conf
ingestor/src/main/scala/weco/concepts/ingestor/IngestStream.scala
ingestor/src/main/scala/weco/concepts/ingestor/Main.scala
ingestor/src/main/scala/weco/concepts/ingestor/model/Identifier.scala
ingestor/src/main/scala/weco/concepts/ingestor/stages/Transformer.scala
ingestor/src/test/scala/weco/concepts/ingestor/stages/TransformerTest.scala

Ingest library of congress names as well as subjects

---

infrastructure/.terraform.lock.hcl
infrastructure/locals.tf
infrastructure/main.tf
infrastructure/run_terraform.sh
infrastructure/stack/elasticsearch.tf
infrastructure/stack/provider.tf
infrastructure/stack/variables.tf
infrastructure/terraform.tf

Just a little cluster for now, but I've set up the networking so we don't forget to connect to it via the VPCE. 
Next up will be provisioning some users in Terraform and making the ingestor put stuff in it!

Create concepts cluster

---

aggregator/README.md
aggregator/docker-compose.yml
aggregator/run_with_remote_cluster.sh
aggregator/src/main/resources/application.conf
aggregator/src/main/scala/weco/concepts/aggregator/BulkUpdateFlow.scala
aggregator/src/main/scala/weco/concepts/aggregator/Indexer.scala
aggregator/src/main/scala/weco/concepts/aggregator/Main.scala
infrastructure/stack/elasticsearch.tf

This includes some bonus improvements to error logging in the aggregator - I implemented these when in pursuit of (what I later discovered to be) https://github.com/elastic/elasticsearch/issues/28923#issuecomment-411395669

Connect local aggregator to remote ES cluster

---

.buildkite/pipeline.yml

Somehow I missed the space between the service name and the build tag

insert missing space

---

aggregator/src/main/scala/weco/concepts/aggregator/ConceptsAggregator.scala
aggregator/src/main/scala/weco/concepts/aggregator/TopicPublisher.scala

Just trying to make it clearer whether things are working correctly

Even more logging

---

aggregator/src/main/scala/weco/concepts/aggregator/ConceptExtractor.scala
aggregator/src/test/scala/weco/concepts/aggregator/testhelpers/ValueGenerators.scala
common/src/main/scala/weco/concepts/common/json/Indexable.scala
common/src/main/scala/weco/concepts/common/model/AuthoritativeConcept.scala
common/src/main/scala/weco/concepts/common/model/Concept.scala
common/src/main/scala/weco/concepts/common/model/Identifier.scala
common/src/main/scala/weco/concepts/common/model/UsedConcept.scala
common/src/test/scala/weco/concepts/common/model/ConceptTest.scala

Following up on https://github.com/wellcomecollection/concepts-pipeline/pull/73#discussion_r1007774332 - in the process of doing it I realised I forgot to write a test for `Indexable[Concept]`, so I did that too.

Make Identifier an Indexable

---

aggregator/src/main/resources/index.json
aggregator/src/main/scala/weco/concepts/aggregator/ConceptExtractor.scala
aggregator/src/test/scala/weco/concepts/aggregator/ConceptExtractorTest.scala
common/src/main/scala/weco/concepts/common/model/UsedConcept.scala
common/src/test/scala/weco/concepts/common/model/UsedConceptTest.scala
recorder/src/main/scala/weco/concepts/recorder/MergeConcepts.scala
recorder/src/test/scala/weco/concepts/recorder/MergeConceptsTest.scala
recorder/src/test/scala/weco/concepts/recorder/RecorderStreamTest.scala

This will require a new index (or to update the. mappings on the existing one) before it will work in real life.

extract ontologyType from catalogue concepts

---

aggregator/bulk.md
aggregator/deduplication.md
aggregator/src/main/resources/reference.conf
aggregator/src/main/resources/remote.conf
aggregator/src/main/scala/weco/concepts/aggregator/ConceptExtractor.scala
aggregator/src/main/scala/weco/concepts/aggregator/ConceptsAggregator.scala
common/src/main/scala/weco/concepts/common/elasticsearch/BulkUpdateFlow.scala
common/src/main/scala/weco/concepts/common/model/CatalogueConcept.scala
common/src/test/scala/weco/concepts/common/model/CatalogueConceptTest.scala
infrastructure/stack/aggregator_lambda.tf
infrastructure/stack/elastic_users.tf
infrastructure/stack/elasticsearch.tf
infrastructure/stack/ingestor_lambda.tf
infrastructure/stack/recorder_lambda.tf
ingestor/src/main/resources/remote.conf
recorder/src/main/resources/reference.conf
recorder/src/main/resources/remote.conf
recorder/src/main/scala/weco/concepts/recorder/BulkLambdaMain.scala
recorder/src/main/scala/weco/concepts/recorder/Main.scala
recorder/src/main/scala/weco/concepts/recorder/MergeConcepts.scala
recorder/src/main/scala/weco/concepts/recorder/RecorderMain.scala
recorder/src/main/scala/weco/concepts/recorder/RecorderStream.scala
recorder/src/test/scala/weco/concepts/recorder/MergeConceptsTest.scala
recorder/src/test/scala/weco/concepts/recorder/RecorderStreamTest.scala

This changes index names as well - I think I'll run everything from scratch in bulk mode tomorrow and we should end up with a squeaky clean cluster

Rename UsedConcept to CatalogueConcept

---

aggregator/src/main/scala/weco/concepts/aggregator/AggregatorMain.scala
aggregator/src/main/scala/weco/concepts/aggregator/ConceptsAggregator.scala
aggregator/src/main/scala/weco/concepts/aggregator/LambdaMain.scala
aggregator/src/main/scala/weco/concepts/aggregator/Main.scala
aggregator/src/main/scala/weco/concepts/aggregator/SQSMain.scala
ingestor/src/main/scala/weco/concepts/ingestor/Main.scala
recorder/src/main/scala/weco/concepts/recorder/Main.scala

- Better logging of success/failure (this is intentionally duplicated as with other app-level boilerplate)
- Option not to publish updates from the aggregator depending on mode of operation

A couple of improvements

---

infrastructure/stack/elastic_users.tf

Not much else to say about this

Provision an ES user for the concepts API

---

common/src/main/scala/weco/concepts/common/model/Concept.scala
common/src/main/scala/weco/concepts/common/model/Identifier.scala
common/src/test/scala/weco/concepts/common/model/ConceptTest.scala
recorder/src/main/resources/index.json

I previously said I didn't want to do this, but actually it's rather useful

Use a display/query index mapping for concepts

---

aggregator/src/main/scala/weco/concepts/aggregator/AggregatorMain.scala
infrastructure/main.tf

Also fixes a bug I introduced in https://github.com/wellcomecollection/concepts-pipeline/pull/84/files

Bump catalogue pipeline date

---

aggregator/src/main/scala/weco/concepts/aggregator/BadIdentifierTypeException.scala
aggregator/src/main/scala/weco/concepts/aggregator/ConceptExtractor.scala
aggregator/src/main/scala/weco/concepts/aggregator/ConceptsAggregator.scala
aggregator/src/main/scala/weco/concepts/aggregator/InvalidArg.scala
aggregator/src/test/scala/weco/concepts/aggregator/ConceptExtractorTest.scala
common/src/main/scala/weco/concepts/common/model/Identifier.scala

Also enforces single identifiers on concepts
Supersedes https://github.com/wellcomecollection/concepts-pipeline/pull/88

Use canonicalId to deduplicate concepts

---

aggregator/src/main/scala/weco/concepts/aggregator/ConceptsAggregator.scala
common/src/main/scala/weco/concepts/common/elasticsearch/BulkUpdateFlow.scala

This wasn't actually causing a bug, but it's still bad

Remove combineMat streams nonsense

---

.buildkite/pipeline.yml
aggregator/src/main/scala/weco/concepts/aggregator/ConceptExtractor.scala
docker-compose.yml
infrastructure/ecr.tf
infrastructure/main.tf
infrastructure/stack/aggregator_lambda.tf
infrastructure/stack/recorder_lambda.tf
infrastructure/stack/variables.tf

This puts the bulk aggregator and bulk recorder on Lambda so we don't have to run them locally.

Bulk aggregator/recorder lambdas

---

infrastructure/main.tf

Use the 2023-02-21 pipeline

---

aggregator/src/main/scala/weco/concepts/aggregator/ConceptExtractor.scala
aggregator/src/test/scala/weco/concepts/aggregator/ConceptExtractorTest.scala

This won't collect anything new yet, as the Works transformers don't create "Genres", but it's part of the general prep for when they do.

Genre as type

---

common/src/main/scala/weco/concepts/common/ResourceLoader.scala
common/src/main/scala/weco/concepts/common/elasticsearch/Creatable.scala
common/src/main/scala/weco/concepts/common/elasticsearch/Indices.scala
common/src/main/scala/weco/concepts/common/elasticsearch/ScriptedBulkUpdateFlow.scala
common/src/main/scala/weco/concepts/common/elasticsearch/Scripts.scala
common/src/main/scala/weco/concepts/common/json/Indexable.scala
common/src/test/scala/weco/concepts/common/elasticsearch/IndicesTest.scala
common/src/test/scala/weco/concepts/common/elasticsearch/ScriptedBulkUpdateFlowTest.scala
common/src/test/scala/weco/concepts/common/elasticsearch/ScriptsTest.scala

Adds the facility to do scripted bulk updates

Scripted bulk

---

aggregator/src/main/scala/weco/concepts/aggregator/AggregatorMain.scala
aggregator/src/main/scala/weco/concepts/aggregator/sources/WorkIdSource.scala
aggregator/src/test/scala/weco/concepts/aggregator/sources/WorkIdSourceTest.scala

https://github.com/wellcomecollection/concepts-pipeline/issues/116

deduplicate workId source
